/* Copyright Statement:
*This firmware are protected under relevant copyright laws,this information contained
*herein is confidential and proprietary to Goodix.
*
* Copyright  (C)  2010 - 2014 Goodix. Ltd.
*
*WARNING:The GTP_COMPATIBLE_MODE part of this file was generated by the specialized tools,
*please do not modify it manually!
*
*/

#ifndef _GT9XX_FIRMWARE_H_
#define _GT9XX_FIRMWARE_H_

unsigned char gtp_9271[] = {
    #include "101143_GT9271_1070_20231107_V130.cfg"
};

#if GTP_HEADER_FW_UPDATE
unsigned char gtp_default_FW[] =
{
            //TODO:Puts your update firmware data here!
};
#endif

/*
*[HW INFO]00900600
*[PID]910
*[VID]1010
*[GENERATED]2013/08/27 20:59:13
*/
#if GTP_COMPATIBLE_MODE
unsigned char gtp_default_FW_fl[] = {
    0x00
};
#endif

#endif